@host=http://localhost:3000

# @name Create Connection
POST {{host}}/bridge/connections
x-admin-api-key: bridge-admin
Content-Type: application/json

{
  "name": "PSSBSA",
  "connectionType": "serviceName",
  "host":"203.95.216.155",
  "port":1556,
  "serviceName":"avt06p",
  "username": "PSSBSA",
  "passwordSecretRef": "env:ORACLE_PASSWORD",
  "defaultOwner": "PSSBSA"
}
###

# @name List Connections
GET {{host}}/bridge/connections
x-admin-api-key: bridge-admin

###
@connection_id=959870a7-9d9c-4bd8-8be3-b4ca09320231

# @name Get Connection Details
GET {{host}}/bridge/connections/{{connection_id}}
x-admin-api-key: bridge-admin

###
# @name Test connection
POST {{host}}/bridge/connections/{{connection_id}}/test
x-admin-api-key: bridge-admin

{}
###
# @name Detect capabilities
POST {{host}}/bridge/connections/{{connection_id}}/detect-capabilities
x-admin-api-key: bridge-admin

{}
###
# @name inspect connection
POST {{host}}/bridge/connections/{{connection_id}}/inspect
x-admin-api-key: bridge-admin
Content-Type: application/json

{
  "owner": "PSSBSA"
}
###

@snapshot_id=<snapshot-id-from-inspect>

# @name List snapshots
GET {{host}}/bridge/schema-snapshots
x-admin-api-key: bridge-admin

###
# @name Get snapshot summary
GET {{host}}/bridge/schema-snapshots/{{snapshot_id}}
x-admin-api-key: bridge-admin

###
# @name List objects (tables/views)
GET {{host}}/bridge/schema-snapshots/{{snapshot_id}}/objects
x-admin-api-key: bridge-admin

###
# @name Get object detail (columns, constraints, indexes)
GET {{host}}/bridge/schema-snapshots/{{snapshot_id}}/objects/SOME_TABLE
x-admin-api-key: bridge-admin

###
# @name List sequences
GET {{host}}/bridge/schema-snapshots/{{snapshot_id}}/sequences
x-admin-api-key: bridge-admin

###
# @name List program units (procedures/functions/packages)
GET {{host}}/bridge/schema-snapshots/{{snapshot_id}}/program-units
x-admin-api-key: bridge-admin

###
# @name Get program unit detail (with arguments)
GET {{host}}/bridge/schema-snapshots/{{snapshot_id}}/program-units/SOME_PROC
x-admin-api-key: bridge-admin

###
# @name Get package member detail (disambiguate with ?package=)
GET {{host}}/bridge/schema-snapshots/{{snapshot_id}}/program-units/SOME_PROC?package=SOME_PKG
x-admin-api-key: bridge-admin

###